// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// C_ransac_bole_slices
DataFrame C_ransac_bole_slices(NumericVector X, NumericVector Y, NumericVector Z, IntegerVector treeIds, NumericVector tree_X, NumericVector tree_Y, IntegerVector tree_ID_vals, double z_min, double z_max, double dz, double overlap, double search_radius, double inlier_tol, int n_samples, double confidence, double inlier_frac, int n_best, double max_radius, int min_pts, int ncpu);
RcppExport SEXP _spanner_C_ransac_bole_slices(SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP treeIdsSEXP, SEXP tree_XSEXP, SEXP tree_YSEXP, SEXP tree_ID_valsSEXP, SEXP z_minSEXP, SEXP z_maxSEXP, SEXP dzSEXP, SEXP overlapSEXP, SEXP search_radiusSEXP, SEXP inlier_tolSEXP, SEXP n_samplesSEXP, SEXP confidenceSEXP, SEXP inlier_fracSEXP, SEXP n_bestSEXP, SEXP max_radiusSEXP, SEXP min_ptsSEXP, SEXP ncpuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type treeIds(treeIdsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tree_X(tree_XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tree_Y(tree_YSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type tree_ID_vals(tree_ID_valsSEXP);
    Rcpp::traits::input_parameter< double >::type z_min(z_minSEXP);
    Rcpp::traits::input_parameter< double >::type z_max(z_maxSEXP);
    Rcpp::traits::input_parameter< double >::type dz(dzSEXP);
    Rcpp::traits::input_parameter< double >::type overlap(overlapSEXP);
    Rcpp::traits::input_parameter< double >::type search_radius(search_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type inlier_tol(inlier_tolSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< double >::type confidence(confidenceSEXP);
    Rcpp::traits::input_parameter< double >::type inlier_frac(inlier_fracSEXP);
    Rcpp::traits::input_parameter< int >::type n_best(n_bestSEXP);
    Rcpp::traits::input_parameter< double >::type max_radius(max_radiusSEXP);
    Rcpp::traits::input_parameter< int >::type min_pts(min_ptsSEXP);
    Rcpp::traits::input_parameter< int >::type ncpu(ncpuSEXP);
    rcpp_result_gen = Rcpp::wrap(C_ransac_bole_slices(X, Y, Z, treeIds, tree_X, tree_Y, tree_ID_vals, z_min, z_max, dz, overlap, search_radius, inlier_tol, n_samples, confidence, inlier_frac, n_best, max_radius, min_pts, ncpu));
    return rcpp_result_gen;
END_RCPP
}
// C_eigen_in_sphere
List C_eigen_in_sphere(S4 las, double r, int k, int ncpu);
RcppExport SEXP _spanner_C_eigen_in_sphere(SEXP lasSEXP, SEXP rSEXP, SEXP kSEXP, SEXP ncpuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type las(lasSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type ncpu(ncpuSEXP);
    rcpp_result_gen = Rcpp::wrap(C_eigen_in_sphere(las, r, k, ncpu));
    return rcpp_result_gen;
END_RCPP
}
// C_count_in_disc
IntegerVector C_count_in_disc(NumericVector X, NumericVector Y, NumericVector x, NumericVector y, double radius, int ncpu);
RcppExport SEXP _spanner_C_count_in_disc(SEXP XSEXP, SEXP YSEXP, SEXP xSEXP, SEXP ySEXP, SEXP radiusSEXP, SEXP ncpuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< int >::type ncpu(ncpuSEXP);
    rcpp_result_gen = Rcpp::wrap(C_count_in_disc(X, Y, x, y, radius, ncpu));
    return rcpp_result_gen;
END_RCPP
}
// C_count_in_sphere
IntegerVector C_count_in_sphere(S4 las, double radius, int ncpu);
RcppExport SEXP _spanner_C_count_in_sphere(SEXP lasSEXP, SEXP radiusSEXP, SEXP ncpuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type las(lasSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< int >::type ncpu(ncpuSEXP);
    rcpp_result_gen = Rcpp::wrap(C_count_in_sphere(las, radius, ncpu));
    return rcpp_result_gen;
END_RCPP
}
// C_knn_majority_vote
List C_knn_majority_vote(IntegerMatrix nn_idx, LogicalVector labels_in, int n_iter, int ncpu);
RcppExport SEXP _spanner_C_knn_majority_vote(SEXP nn_idxSEXP, SEXP labels_inSEXP, SEXP n_iterSEXP, SEXP ncpuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type nn_idx(nn_idxSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type labels_in(labels_inSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type ncpu(ncpuSEXP);
    rcpp_result_gen = Rcpp::wrap(C_knn_majority_vote(nn_idx, labels_in, n_iter, ncpu));
    return rcpp_result_gen;
END_RCPP
}
// C_voxelize_pad
List C_voxelize_pad(NumericVector x, NumericVector y, NumericVector z, double vox_size, int ncpu);
RcppExport SEXP _spanner_C_voxelize_pad(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP vox_sizeSEXP, SEXP ncpuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type vox_size(vox_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type ncpu(ncpuSEXP);
    rcpp_result_gen = Rcpp::wrap(C_voxelize_pad(x, y, z, vox_size, ncpu));
    return rcpp_result_gen;
END_RCPP
}
// C_voxelize_pad_rays
List C_voxelize_pad_rays(NumericVector x, NumericVector y, NumericVector z, NumericVector sx, NumericVector sy, NumericVector sz, double vox_size, int ncpu);
RcppExport SEXP _spanner_C_voxelize_pad_rays(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP sxSEXP, SEXP sySEXP, SEXP szSEXP, SEXP vox_sizeSEXP, SEXP ncpuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sx(sxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sy(sySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sz(szSEXP);
    Rcpp::traits::input_parameter< double >::type vox_size(vox_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type ncpu(ncpuSEXP);
    rcpp_result_gen = Rcpp::wrap(C_voxelize_pad_rays(x, y, z, sx, sy, sz, vox_size, ncpu));
    return rcpp_result_gen;
END_RCPP
}
// cppCylinderFit
SEXP cppCylinderFit(NumericMatrix& las, std::string method, unsigned int n, double p, double inliers, double max_angle, unsigned int n_best);
RcppExport SEXP _spanner_cppCylinderFit(SEXP lasSEXP, SEXP methodSEXP, SEXP nSEXP, SEXP pSEXP, SEXP inliersSEXP, SEXP max_angleSEXP, SEXP n_bestSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type las(lasSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type inliers(inliersSEXP);
    Rcpp::traits::input_parameter< double >::type max_angle(max_angleSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_best(n_bestSEXP);
    rcpp_result_gen = Rcpp::wrap(cppCylinderFit(las, method, n, p, inliers, max_angle, n_best));
    return rcpp_result_gen;
END_RCPP
}
// cppComputePCV
SEXP cppComputePCV(S4 las, double radius, int num_directions, int ncpu);
RcppExport SEXP _spanner_cppComputePCV(SEXP lasSEXP, SEXP radiusSEXP, SEXP num_directionsSEXP, SEXP ncpuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type las(lasSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< int >::type num_directions(num_directionsSEXP);
    Rcpp::traits::input_parameter< int >::type ncpu(ncpuSEXP);
    rcpp_result_gen = Rcpp::wrap(cppComputePCV(las, radius, num_directions, ncpu));
    return rcpp_result_gen;
END_RCPP
}
// cppComputeSSAO
NumericVector cppComputeSSAO(S4 las, int kernel_size, double pixel_size, int num_samples, int ncpu);
RcppExport SEXP _spanner_cppComputeSSAO(SEXP lasSEXP, SEXP kernel_sizeSEXP, SEXP pixel_sizeSEXP, SEXP num_samplesSEXP, SEXP ncpuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type las(lasSEXP);
    Rcpp::traits::input_parameter< int >::type kernel_size(kernel_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type pixel_size(pixel_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type num_samples(num_samplesSEXP);
    Rcpp::traits::input_parameter< int >::type ncpu(ncpuSEXP);
    rcpp_result_gen = Rcpp::wrap(cppComputeSSAO(las, kernel_size, pixel_size, num_samples, ncpu));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP cpp_allometric_li_geodesic(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP cpp_allometric_random_walker(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP cpp_allometric_supervoxel_segment(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_spanner_C_ransac_bole_slices", (DL_FUNC) &_spanner_C_ransac_bole_slices, 20},
    {"_spanner_C_eigen_in_sphere", (DL_FUNC) &_spanner_C_eigen_in_sphere, 4},
    {"_spanner_C_count_in_disc", (DL_FUNC) &_spanner_C_count_in_disc, 6},
    {"_spanner_C_count_in_sphere", (DL_FUNC) &_spanner_C_count_in_sphere, 3},
    {"_spanner_C_knn_majority_vote", (DL_FUNC) &_spanner_C_knn_majority_vote, 4},
    {"_spanner_C_voxelize_pad", (DL_FUNC) &_spanner_C_voxelize_pad, 5},
    {"_spanner_C_voxelize_pad_rays", (DL_FUNC) &_spanner_C_voxelize_pad_rays, 8},
    {"_spanner_cppCylinderFit", (DL_FUNC) &_spanner_cppCylinderFit, 7},
    {"_spanner_cppComputePCV", (DL_FUNC) &_spanner_cppComputePCV, 4},
    {"_spanner_cppComputeSSAO", (DL_FUNC) &_spanner_cppComputeSSAO, 5},
    {"cpp_allometric_li_geodesic",        (DL_FUNC) &cpp_allometric_li_geodesic,        20},
    {"cpp_allometric_random_walker",      (DL_FUNC) &cpp_allometric_random_walker,      18},
    {"cpp_allometric_supervoxel_segment", (DL_FUNC) &cpp_allometric_supervoxel_segment, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_spanner(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
