# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_eigen_in_sphere <- function(las, radius, ncpu) {
    .Call(`_spanner_C_eigen_in_sphere`, las, radius, ncpu)
}

C_count_in_disc <- function(X, Y, x, y, radius, ncpu) {
    .Call(`_spanner_C_count_in_disc`, X, Y, x, y, radius, ncpu)
}

C_count_in_sphere <- function(las, radius, ncpu) {
    .Call(`_spanner_C_count_in_sphere`, las, radius, ncpu)
}

