# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_eigen_in_sphere <- function(las, r, k, ncpu) {
    .Call(`_spanner_C_eigen_in_sphere`, las, r, k, ncpu)
}

C_count_in_disc <- function(X, Y, x, y, radius, ncpu) {
    .Call(`_spanner_C_count_in_disc`, X, Y, x, y, radius, ncpu)
}

C_count_in_sphere <- function(las, radius, ncpu) {
    .Call(`_spanner_C_count_in_sphere`, las, radius, ncpu)
}

C_knn_majority_vote <- function(nn_idx, labels_in, n_iter, ncpu = 1L) {
    .Call(`_spanner_C_knn_majority_vote`, nn_idx, labels_in, n_iter, ncpu)
}

C_voxelize_pad <- function(x, y, z, vox_size, ncpu = 1L) {
    .Call(`_spanner_C_voxelize_pad`, x, y, z, vox_size, ncpu)
}

C_voxelize_pad_rays <- function(x, y, z, sx, sy, sz, vox_size, ncpu = 1L) {
    .Call(`_spanner_C_voxelize_pad_rays`, x, y, z, sx, sy, sz, vox_size, ncpu)
}

cppCylinderFit <- function(las, method = "nm", n = 10L, p = 0.95, inliers = 0.9, max_angle = 30, n_best = 20L) {
    .Call(`_spanner_cppCylinderFit`, las, method, n, p, inliers, max_angle, n_best)
}

cppComputePCV <- function(las, radius = 1.0, num_directions = 60L, ncpu = 1L) {
    .Call(`_spanner_cppComputePCV`, las, radius, num_directions, ncpu)
}

cppComputeSSAO <- function(las, kernel_size = 5L, pixel_size = 0.1, num_samples = 16L, ncpu = 4L) {
    .Call(`_spanner_cppComputeSSAO`, las, kernel_size, pixel_size, num_samples, ncpu)
}

C_stack_map <- function(las, h_min = 1.0, h_max = 3.0, h_step = 0.5, pixel_size = 0.025, max_radius = 0.25, min_density = 0.1, min_votes = 3L) {
    .Call(`_spanner_C_stack_map`, las, h_min, h_max, h_step, pixel_size, max_radius, min_density, min_votes)
}

C_hough_stem_points <- function(las, h_base_lo = 1.0, h_base_hi = 2.5, h_step = 0.5, max_radius = 0.25, pixel_size = 0.025, min_density = 0.1, min_votes = 3L) {
    .Call(`_spanner_C_hough_stem_points`, las, h_base_lo, h_base_hi, h_step, max_radius, pixel_size, min_density, min_votes)
}

C_hough_stem_plot <- function(las, tree_ids, h_base_lo = 1.0, h_base_hi = 2.5, h_step = 0.5, max_radius = 0.25, pixel_size = 0.025, min_density = 0.1, min_votes = 3L) {
    .Call(`_spanner_C_hough_stem_plot`, las, tree_ids, h_base_lo, h_base_hi, h_step, max_radius, pixel_size, min_density, min_votes)
}

C_tree_ids_voronoi <- function(pt_x, pt_y, tree_x, tree_y, tree_ids, max_dist = -1.0) {
    .Call(`_spanner_C_tree_ids_voronoi`, pt_x, pt_y, tree_x, tree_y, tree_ids, max_dist)
}

C_tree_ids_crop <- function(pt_x, pt_y, tree_x, tree_y, tree_ids, length = 1.0, circle = TRUE) {
    .Call(`_spanner_C_tree_ids_crop`, pt_x, pt_y, tree_x, tree_y, tree_ids, length, circle)
}

C_ransac_plot_cylinders <- function(las, tId, segs, rads, n_samples = 10L, conf = 0.95, inlier_frac = 0.9, tol = 0.05) {
    .Call(`_spanner_C_ransac_plot_cylinders`, las, tId, segs, rads, n_samples, conf, inlier_frac, tol)
}

C_irls_plot_cylinders <- function(las, tId, segs, rads, n_points = 100L, tol = 0.05) {
    .Call(`_spanner_C_irls_plot_cylinders`, las, tId, segs, rads, n_points, tol)
}

C_ransac_stem_slices <- function(X, Y, Z, treeIds, tree_X, tree_Y, tree_ID_vals, z_min, z_max, dz, overlap, search_radius, inlier_tol, n_samples, confidence, inlier_frac, n_best, max_radius, min_pts, ncpu) {
    .Call(`_spanner_C_ransac_stem_slices`, X, Y, Z, treeIds, tree_X, tree_Y, tree_ID_vals, z_min, z_max, dz, overlap, search_radius, inlier_tol, n_samples, confidence, inlier_frac, n_best, max_radius, min_pts, ncpu)
}

